name: EasyRoll Smart Blind
version: 1.9
slug: easyroll
description: Add-on for EasyRoll Smart Blind
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
url: https://github.com/harwin1/ha-addons/blob/main/easyroll_blind
startup: application
boot: auto
uart: true
options:
  mqtt_ssl: false
  blind: []
  mqtt: 
    - server: 192.168.1.1
      port: 1883
      user: null
      passwd: null
  mqtt_ssl_certificate:
    - ca_path: /share/easyroll_blind/ca.crt
      cert_path: /share/easyroll_blind/client.crt
      key_path: /share/easyroll_blind/client.key
  scan_interval: 900  
schema:
  mqtt_ssl: bool
  blind: 
    - str  
  mqtt: 
    - server: str
      port: int
      user: str?
      passwd: str?
  mqtt_ssl_certificate:
    - ca_path: str?
      cert_path: str?
      key_path: str?
  scan_interval: int
