name: EasyRoll Smart Blind
version: 1.7
slug: easyroll
description: Add-on for EasyRoll Smart Blind
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
url: https://github.com/harwin1/ha-addons/blob/main/easyroll_blind
startup: application
boot: auto
uart: true
options:
  blind: []
  mqtt: 
    - server: 192.168.1.1
      port: 1883
      user: null
      passwd: null
  scan_interval: 300  
  command_interval: 40
schema:
  blind: 
    - str  
  mqtt: 
    - server: str
      port: int
      user: str?
      passwd: str?
  scan_interval: int
  command_interval: int
